### ISSUE TITLE
aren't the descriptions supposed to be left aligned while viewing in phones?

### ISSUE THREAD

**Issue by yedhink** [mohitrajane/icefoss19#20]
like while viewing in phones, the descriptions under certain sections are centrally aligned, whereas some other are left aligned. Shouldn't it be either all centrally aligned or left aligned? A mix of both looks kinda weird.  

![23 10 09_2019-02-09_604x688](https://user-images.githubusercontent.com/31244999/52516139-c6bdaf00-2c4b-11e9-9f37-fe79b296a9a9.png)  

![55 10 09_2019-02-09_604x678](https://user-images.githubusercontent.com/31244999/52516140-ccb39000-2c4b-11e9-8e1c-e38f80bf75a8.png)

**Comment by mohitrajane** [comment]
Will look into it asap
